# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/proto/transit.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "valhalla.mjolnir.Transit" do
    repeated :nodes, :message, 1, "valhalla.mjolnir.Transit.Node"
    repeated :stop_pairs, :message, 2, "valhalla.mjolnir.Transit.StopPair"
    repeated :routes, :message, 3, "valhalla.mjolnir.Transit.Route"
    repeated :shapes, :message, 4, "valhalla.mjolnir.Transit.Shape"
  end
  add_message "valhalla.mjolnir.Transit.Node" do
    optional :lon, :float, 1
    optional :lat, :float, 2
    optional :type, :uint32, 3
    optional :graphid, :uint64, 4
    optional :prev_type_graphid, :uint64, 5
    optional :name, :string, 6
    optional :onestop_id, :string, 7
    optional :osm_way_id, :uint64, 8
    optional :timezone, :string, 9
    optional :wheelchair_boarding, :bool, 10
    optional :generated, :bool, 11
    optional :traversability, :uint32, 12
  end
  add_message "valhalla.mjolnir.Transit.StopPair" do
    optional :bikes_allowed, :bool, 1
    optional :block_id, :uint32, 2
    optional :destination_arrival_time, :uint32, 3
    optional :destination_graphid, :uint64, 4
    optional :destination_onestop_id, :string, 5
    optional :operated_by_onestop_id, :string, 6
    optional :origin_departure_time, :uint32, 7
    optional :origin_graphid, :uint64, 8
    optional :origin_onestop_id, :string, 9
    optional :route_index, :uint32, 10
    repeated :service_added_dates, :uint32, 11
    repeated :service_days_of_week, :bool, 12
    optional :service_end_date, :uint32, 13
    repeated :service_except_dates, :uint32, 14
    optional :service_start_date, :uint32, 15
    optional :trip_headsign, :string, 16
    optional :trip_id, :uint32, 17
    optional :wheelchair_accessible, :bool, 18
    optional :shape_id, :uint32, 20
    optional :origin_dist_traveled, :float, 21
    optional :destination_dist_traveled, :float, 22
    optional :frequency_end_time, :uint32, 23
    optional :frequency_headway_seconds, :uint32, 24
  end
  add_message "valhalla.mjolnir.Transit.Route" do
    optional :name, :string, 1
    optional :onestop_id, :string, 2
    optional :operated_by_name, :string, 3
    optional :operated_by_onestop_id, :string, 4
    optional :operated_by_website, :string, 5
    optional :route_color, :uint32, 6
    optional :route_desc, :string, 7
    optional :route_long_name, :string, 8
    optional :route_text_color, :uint32, 9
    optional :vehicle_type, :enum, 10, "valhalla.mjolnir.Transit.VehicleType"
  end
  add_message "valhalla.mjolnir.Transit.Shape" do
    optional :shape_id, :uint32, 1
    optional :encoded_shape, :bytes, 2
  end
  add_enum "valhalla.mjolnir.Transit.VehicleType" do
    value :Tram, 0
    value :Metro, 1
    value :Rail, 2
    value :Bus, 3
    value :Ferry, 4
    value :CableCar, 5
    value :Gondola, 6
    value :Funicular, 7
  end
end

module Valhalla
  module Mjolnir
    Transit = Google::Protobuf::DescriptorPool.generated_pool.lookup("valhalla.mjolnir.Transit").msgclass
    Transit::Node = Google::Protobuf::DescriptorPool.generated_pool.lookup("valhalla.mjolnir.Transit.Node").msgclass
    Transit::StopPair = Google::Protobuf::DescriptorPool.generated_pool.lookup("valhalla.mjolnir.Transit.StopPair").msgclass
    Transit::Route = Google::Protobuf::DescriptorPool.generated_pool.lookup("valhalla.mjolnir.Transit.Route").msgclass
    Transit::Shape = Google::Protobuf::DescriptorPool.generated_pool.lookup("valhalla.mjolnir.Transit.Shape").msgclass
    Transit::VehicleType = Google::Protobuf::DescriptorPool.generated_pool.lookup("valhalla.mjolnir.Transit.VehicleType").enummodule
  end
end
